spring:
  application:
    name: franchise-api
  
  # Conexión a MongoDB Atlas
  data:
    mongodb:
      uri: mongodb+srv://yersonluna:m4lKOfCVK97DME4B@cluster0.nt7pija.mongodb.net/franchise_db?retryWrites=true&w=majority&appName=Cluster0

  # Importante: Desactivamos el soporte de Docker Compose para evitar conflictos
  docker:
    compose:
      enabled: false

  webflux:
    base-path: /api

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.franchise: DEBUG